# Generated by Django 5.0.4 on 2024-04-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_journal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='data',
            name='group',
            field=models.CharField(max_length=50, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='data',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
    ]
